# Generated by Django 6.0.2 on 2026-03-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('vendeur', 'Vendeur')], max_length=20),
        ),
    ]
