# Generated by Django 6.0.2 on 2026-04-01 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taille', models.CharField(max_length=10)),
                ('couleur', models.CharField(max_length=30)),
                ('quantite', models.IntegerField(default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='Base.produit')),
            ],
            options={
                'unique_together': {('produit', 'taille', 'couleur')},
            },
        ),
    ]
