# Generated by Django 6.0.2 on 2026-04-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='est_nouveau',
            field=models.BooleanField(default=False),
        ),
    ]
