# Generated by Django 6.0.2 on 2026-04-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_produit_est_nouveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='genre',
            field=models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme'), ('enfant', 'Enfant'), ('mixte', 'Mixte')], default='mixte', max_length=10),
        ),
    ]
