# Generated by Django 6.0.2 on 2026-04-07 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_produit_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiteBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('visite_boutique', 'Visite boutique'), ('visite_produit', 'Visite produit'), ('clic_whatsapp', 'Clic WhatsApp'), ('clic_commander', 'Clic Commander'), ('filtre_genre', 'Filtre genre'), ('filtre_categorie', 'Filtre catégorie'), ('recherche', 'Recherche'), ('visite_contact', 'Visite contact'), ('visite_equipe', 'Visite équipe'), ('visite_missions', 'Visite missions')], max_length=50)),
                ('produit_id', models.IntegerField(blank=True, null=True)),
                ('produit_nom', models.CharField(blank=True, max_length=200)),
                ('genre', models.CharField(blank=True, max_length=20)),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('recherche', models.CharField(blank=True, max_length=200)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
