# Generated by Django 6.0.2 on 2026-04-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='video_facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Vidéo Facebook'),
        ),
        migrations.AddField(
            model_name='produit',
            name='video_instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Vidéo Instagram / Reels'),
        ),
        migrations.AddField(
            model_name='produit',
            name='video_tiktok',
            field=models.URLField(blank=True, null=True, verbose_name='Vidéo TikTok'),
        ),
    ]
