# Generated by Django 6.0.2 on 2026-04-18 00:48

import Base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_produit_video_facebook_produit_video_instagram_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', Base.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('vendeur', 'Vendeur')], default='vendeur', max_length=20),
        ),
    ]
