# Generated by Django 6.0.2 on 2026-05-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0012_alter_user_managers_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='couleur',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='taille',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
