# Generated by Django 6.0.2 on 2026-05-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0013_alter_stock_couleur_alter_stock_taille'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='type_produit',
            field=models.CharField(choices=[('vetement', 'Vêtement'), ('chaussure', 'Chaussure'), ('sac', 'Sac'), ('parfum', 'Parfum'), ('bijou', 'Bijou'), ('autre', 'Autre')], default='vetement', max_length=20),
        ),
        migrations.AlterField(
            model_name='produit',
            name='video_facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='video_instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='video_tiktok',
            field=models.URLField(blank=True, null=True),
        ),
    ]
